lista_de_palavras = (
    "abacate", "abstrato", "amor", "aquarela", "autentico", "agil", "binario", "bola", "brilhante", "brisa", "bussola",
    "bipolar", "cachorro", "caleidoscopio", "coragem", "criptografico", "ciclico", "cupula", "dado", "degrade",
    "dialogo",
    "dinamica", "dinamico", "distopico", "eclipse", "efemero", "elefante", "empatia", "esferico", "exotico",
    "felicidade",
    "fenix", "ficticio", "foca", "fluorescente", "fragmentado", "geometria", "girafa", "gnostico", "gorgona",
    "gratidão",
    "glacial", "harmônico", "helice", "holografico", "hortelã", "hibrido", "icônico", "idilico", "inovação",
    "iridescente",
    "icaro", "indigo", "jacare", "jasmim", "jocoso", "jovial", "justaposto", "ketchup",
    "kilobyte",
    "kiwi", "labirinto", "lateral", "liberdade", "metamorfose",
    "mistico", "morbido", "musica", "macaco", "nebuloso", "nectar", "nostalgico", "natureza", "nômade", "oasis",
    "obliquo",
    "onirico", "organico", "otimismo", "oculos", "paz", "pictorico", "polimorfo", "pulsar", "papagaio", "prismatico",
    "quantico", "quasar", "querubim", "quimera", "quixotesco", "rapsodico", "requiem", "respeito", "ritmico", "robusto",
    "rato", "sequencial", "sinfonia", "sinuoso", "sinceridade", "sistemico", "sol", "sinuoso", "sequencial", "tatico",
    "tatu", "teorico", "tranquilidade", "tunel", "turbulento", "uni", "unissono", "universo", "utopico", "urso",
    "vanguarda", "vela", "vetorial", "vibrante", "volatil", "visão", "wafer", "wabi-sabi", "waifu", "waffle", "wok",
    "xadrez", "xarope", "xenofilia", "xenofobia", "xenônio", "xerofilo", "yacht", "yard", "yen", "yang", "yucca", "zen",
    "zebra", "zenite", "zigurate")
